### ISSUE TITLE
0.3.4版tpm不工作

### ISSUE THREAD

**Issue by charliealexander73** [kmcsr/tpmanager_mcdr#2]
这是加载插件的时候控制台的报错信息

**Comment by charliealexander73** [comment]
[MCDR] [21:32:35] [TaskExecutor/ERROR]: Fail to load the entry point of tpm@0.3.4
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\mcdreforged\plugin\type\multi_file_plugin.py", line 66, in _on_ready
    self._load_entry_instance()
  File "C:\Program Files\Python311\Lib\site-packages\mcdreforged\plugin\type\regular_plugin.py", line 66, in _load_entry_instance
    self.entry_module_instance = self._import_entrypoint_module()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\mcdreforged\plugin\type\multi_file_plugin.py", line 34, in _import_entrypoint_module
    mod = importlib.import_module(self.get_metadata().entrypoint)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "plugins\TpManager.mcdr\tpm\__init__.py", line 7, in <module>
    from . import commands as CMD
  File "plugins\TpManager.mcdr\tpm\commands.py", line 32, in <module>
    class Commands(PermCommandSet):
  File "plugins\TpManager.mcdr\tpm\commands.py", line 53, in Commands
    @player_only
     ^^^^^^^^^^^
  File "plugins\KPI-v1.4.7.mcdr\kpi\command.py", line 75, in player_only
    return Requires(lambda src: src.is_player,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\KPI-v1.4.7.mcdr\kpi\command.py", line 45, in wrapper
    return functools.wraps(fn)(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\functools.py", line 61, in update_wrapper
    wrapper.__wrapped__ = wrapped
    ^^^^^^^^^^^^^^^^^^^
AttributeError: property '__wrapped__' of 'Requires' object has no setter

**Comment by charliealexander73** [comment]
控制台最后显示插件已加载，但是使用命令!!tp没有反应

**Comment by TheFunny** [comment]
应该是 kpi 的问题，可以临时更换为 kpi 1.4.4，可以成功加载插件。
