### ISSUE TITLE
报错Fail to load the entry point of tpm@0.5.0

### ISSUE THREAD

**Issue by Small-Miao** [kmcsr/tpmanager_mcdr#7]
[MCDR] [2024-09-26 05:48:36.331] [MainThread/INFO] [mcdr_server.py:615(__on_mcdr_start)]: MCDReforged 2.13.2 正在启动
[MCDR] [2024-09-26 05:48:36.335] [MainThread/INFO] [python_plugin.py:36(load)]: MCDReforged 正于 Python 3.12.6 环境中运行
[MCDR] [2024-09-26 05:48:36.354] [TaskExecutor/INFO] [meta_holder.py:203(__load_cached_file)]: 已从缓存文件加载插件仓库元数据 (更新于 2024-09-26 05:02:14)
[MCDR] [2024-09-26 05:48:36.355] [TaskExecutor/INFO] [plugin_manager.py:693(refresh_all_plugins_action)]: 刷新所有插件中
[MCDR] [2024-09-26 05:48:36.396] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 quick_backup_multi@1.10.1 已加载
[MCDR] [2024-09-26 05:48:36.397] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 hat@1.0.1 已加载
[MCDR] [2024-09-26 05:48:36.399] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 minecraft_data_api@1.5.0 已加载
[MCDR] [2024-09-26 05:48:36.400] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 here@1.2.2 已加载
[MCDR] [2024-09-26 05:48:36.401] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 kpi@1.4.7 已加载
[MCDR] [2024-09-26 05:48:36.401] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 online_player_api@1.0.0 已加载
[MCDR] [2024-09-26 05:48:36.402] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 beep@1.1.0 已加载
[MCDR] [2024-09-26 05:48:36.402] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 advanced_calculator@0.3.1 已加载
[MCDR] [2024-09-26 05:48:36.403] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 tpm@0.5.0 已加载
[MCDR] [2024-09-26 05:48:36.498] [TaskExecutor/ERROR] [multi_file_plugin.py:88(_on_ready)]: Fail to load the entry point of tpm@0.5.0
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/mcdreforged/plugin/type/multi_file_plugin.py", line 86, in _on_ready
    self._load_entry_instance()
  File "/usr/local/lib/python3.12/site-packages/mcdreforged/plugin/type/regular_plugin.py", line 79, in _load_entry_instance
    self.entry_module_instance = self._import_entrypoint_module()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mcdreforged/plugin/type/multi_file_plugin.py", line 51, in _import_entrypoint_module
    mod = importlib.import_module(self.get_metadata().entrypoint)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "plugins/TpManager-v0.5.0.mcdr/tpm/__init__.py", line 7, in <module>
    from . import commands as CMD
  File "plugins/TpManager-v0.5.0.mcdr/tpm/commands.py", line 44, in <module>
    class Commands(PermCommandSet):
  File "plugins/TpManager-v0.5.0.mcdr/tpm/commands.py", line 71, in Commands
    @player_only
     ^^^^^^^^^^^
  File "plugins/KPI-v1.4.7.mcdr/kpi/command.py", line 75, in player_only
    return Requires(lambda src: src.is_player,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/KPI-v1.4.7.mcdr/kpi/command.py", line 45, in wrapper
    return functools.wraps(fn)(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 61, in update_wrapper
    wrapper.__wrapped__ = wrapped
    ^^^^^^^^^^^^^^^^^^^
AttributeError: property '__wrapped__' of 'Requires' object has no setter
[MCDR] [2024-09-26 05:48:36.508] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [quick_backup_multi]: 配置文件已加载
[MCDR] [2024-09-26 05:48:36.509] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [hat]: 配置文件已加载
[MCDR] [2024-09-26 05:48:36.509] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [here]: 配置文件已加载
[MCDR] [2024-09-26 05:48:36.510] [TaskExecutor/INFO] [mcdr_server.py:294(load_plugins)]: 共加载: §79§r 个插件; 已加载插件数: §711§r
[MCDR] [2024-09-26 05:48:36.515] [MainThread/INFO] [mcdr_server.py:409(start_server)]: 正在启动服务端，启动参数为 '/www/wwwroot/mcdr/javaruntime/jdk-22.0.1/bin/java -javaagent:authlib-injector-1.2.5.jar=http://skin.centralteam.cn/api/yggdrasil @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.20.1-47.3.7/unix_args.txt "$@"'
[MCDR] [2024-09-26 05:48:36.523] [MainThread/INFO] [mcdr_server.py:491(__on_server_start)]: 服务端正在以 PID 78783 运行中
[MCDR] [2024-09-26 05:48:37.556] [CheckUpdate/INFO] [update_helper.py:73(__check_update)]: MCDR 已为最新版

**Comment by lnbiuc** [comment]
same problem
